# Generated by Django 4.1.4 on 2024-05-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(default=0, max_length=15),
        ),
    ]
