# Generated by Django 4.1.4 on 2024-05-01 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_user_phonenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_name", models.CharField(max_length=100)),
                ("number_of_tickets", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_of_expiry", models.DateTimeField()),
                ("type", models.CharField(max_length=20)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
