# Generated by Django 4.1.4 on 2024-05-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact", name="queries", field=models.TextField(max_length=90),
        ),
    ]
