# Generated by Django 4.1.4 on 2024-05-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
