# Generated by Django 4.1.4 on 2024-05-07 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_alter_user_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="ticket",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.ticket",
            ),
            preserve_default=False,
        ),
    ]
