# Generated by Django 4.1.4 on 2024-05-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_book_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_name", models.CharField(max_length=20)),
                ("uploaded_by", models.CharField(max_length=20)),
                ("complaint_by", models.CharField(max_length=20)),
                ("ticket_price", models.CharField(max_length=20)),
                ("actual_price", models.CharField(max_length=20)),
            ],
        ),
    ]
