# Generated by Django 4.1.4 on 2024-05-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_complaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="book", name="payment", field=models.BooleanField(default=0),
        ),
    ]
