# Generated by Django 5.2 on 2025-05-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_book_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
