# Generated by Django 5.2 on 2025-05-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_ticket_ticket_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_file',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_images/'),
        ),
    ]
